### ISSUE TITLE
Smooth Tracks operation not working due to "copy" not definded

### ISSUE THREAD

**Issue by chansheunglong** [mattshepcar/easyeda-round-tracks#8]
The smooth tracks operation cannot be performed after EasyEDA's recent update, attached is the log. I have tested on Google Chrome and Microsoft Edge and can confirm it is not a browser-specific issue. It seems that EasyEDA has changed its API.

IMO EasyEDA should consider adding this as a built-in feature.

```
VM556:28 Loading board
VM556:32 Cleaning up overlapping tracks
VM555:172 Uncaught ReferenceError: copy is not defined
    at cleanupColinearTrackPair (eval at <anonymous> (main.min.js:20:13167), <anonymous>:172:17)
    at Board.cleanupColinearTracks (eval at <anonymous> (main.min.js:20:13167), <anonymous>:46:29)
    at new Board (eval at <anonymous> (main.min.js:20:13167), <anonymous>:33:14)
    at eval (eval at <anonymous> (main.min.js:20:13167), <anonymous>:41:13)
    at Object.doCommand (main.min.js:21:1880)
    at easyeda.extension.doCommand (main.min.js:20:16111)
    at HTMLDivElement.Cn (main.min.js:6:19874)
    at HTMLDivElement.<anonymous> (main.min.js:88:28832)
    at HTMLDocument.dispatch (main.assets.min.js:3:11580)
    at HTMLDocument.s (main.assets.min.js:3:7469)
cleanupColinearTrackPair @ VM555:172
cleanupColinearTracks @ VM556:46
Board @ VM556:33
eval @ VM560:41
doCommand @ main.min.js:21
easyeda.extension.doCommand @ main.min.js:20
Cn @ main.min.js:6
(anonymous) @ main.min.js:88
dispatch @ main.assets.min.js:3
s @ main.assets.min.js:3
```

**Comment by chansheunglong** [comment]
I am closing this issue as it seems that EasyEDA has fixed itself and there is now no problem using this extension.

For anyone who are wondering, it works on

> Version : V6.5.22
> BuildDate : 10/27/2022
